language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t rutvijkanzaria/docker-react -f Dockerfile.dev .
    - docker run -e CI=true rutvijkanzaria/docker-react yarn test